# Generated by Django 2.2.6 on 2019-10-04 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_system', '0002_trial_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitanswer',
            name='result',
        ),
        migrations.AddField(
            model_name='recruitanswer',
            name='recruit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recruiting_system.Recruit', verbose_name='Рекрут'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trial',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
