# Generated by Django 2.2.6 on 2019-10-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_system', '0003_auto_20191004_1619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruitanswer',
            unique_together={('question', 'recruit')},
        ),
    ]
